"""Update project members association table

Revision ID: f7d60259d388
Revises: 
Create Date: 2025-05-06 08:40:38.391485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d60259d388'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=True),
    sa.Column('developer_tag', sa.String(length=50), nullable=False),
    sa.Column('two_fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_fa_verified', sa.Boolean(), nullable=True),
    sa.Column('api_key', sa.String(length=40), nullable=True),
    sa.Column('api_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('developer_tag'),
    sa.UniqueConstraint('email')
    )
    op.create_table('project',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.developer_tag'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('time_worked', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('developer_tag', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['developer_tag'], ['user.developer_tag'], ),
    sa.ForeignKeyConstraint(['project_name'], ['project.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_members',
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_name'], ['project.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.developer_tag'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_members')
    op.drop_table('log_entry')
    op.drop_table('project')
    op.drop_table('user')
    # ### end Alembic commands ###
